export const baseUrl = 'http://localhost:3000'
export const loginUrl = 'api/auth/login'
export const logoutUrl = 'api/auth/logout'
export const projectUrl = 'api/projects'
export const employeesUrl = 'api/employees'
